backend:
  name: github
  repo: ChaituKNag/TheBestDeveloper
  branch: site

media_folder: site/static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: site/static/blog
    description: All the technical blogs of my site.
    create: true
    slug: "{{year}}-{{month}}-{{date}}__{{slug}}"
    fields:
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime, required: true }
      - { name: title, label: Title, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: tags, label: Tags, widget: list, required: true }
