backend:
  name: github
  repo: ChaituKNag/TheBestDeveloper
  branch: site

media_folder: site/static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: site/static/blog
    description: All the technical blogs of my site.
    create: true
    slug: "{{year}}-{{month}}-{{date}}__{{slug}}"
    fields:
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime, required: true }
      - { name: title, label: Title, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: tags, label: Tags, widget: list, required: true }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home-page"
        file: "site/static/content/home-page.yml"
        fields:
          - { label: Salutation, name: salutation, widget: string }
          - { label: Bio, name: bio, widget: string }
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Id, name: id, widget: string }
              - { label: Link, name: link, widget: string }
          - { label: Project Intro, name: projectIntro, widget: string }
          - { label: Fun Stuff Intro, name: funStuffIntro, widget: string }
